# Generated by Django 3.1 on 2020-09-09 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(default='SOME STRING')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.CharField(default='SOME STRING', max_length=100)),
                ('city', models.CharField(choices=[('Istanbul', 'Izmir'), ('Denizli', 'Antalya'), ('Aydin', 'Rize')], default=0, max_length=15)),
                ('product', models.CharField(choices=[('apple', 'banana'), ('orange', 'peach'), ('strawberry', 'kiwi'), ('coconut', 'avocado'), ('watermelon', 'cherry')], default=0, max_length=15)),
                ('product_type', models.CharField(blank=True, default='SOME STRING', max_length=15)),
                ('amount', models.CharField(blank=True, default='SOME STRING', max_length=15)),
                ('price', models.CharField(blank=True, default='SOME STRING', max_length=15)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(choices=[('Fruits', 'Veggies'), ('Nuts', 'Honey'), ('Tea', 'Legumes'), ('Oil', 'Wheat'), ('Flowers', 'Mushroom')], on_delete=django.db.models.deletion.CASCADE, to='digitalFarm.category')),
            ],
        ),
    ]
