# Generated by Django 3.1 on 2020-08-31 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(default='SOME STRING')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.CharField(default='SOME STRING', max_length=100)),
                ('category', models.CharField(choices=[('Fruits', 'Veggies'), ('Nuts', 'Honey'), ('Tea', 'Legumes'), ('Oil', 'Wheat'), ('Flowers', 'Mushroom')], default='Fruits', max_length=15)),
                ('city', models.CharField(choices=[('Istanbul', 'Izmir'), ('Denizli', 'Antalya'), ('Aydin', 'Rize')], default='Istanbul', max_length=15)),
                ('product', models.CharField(choices=[('apple', 'banana'), ('orange', 'peach'), ('strawberry', 'kiwi'), ('coconut', 'avocado'), ('watermelon', 'cherry')], default='apple', max_length=15)),
                ('product_type', models.CharField(blank=True, default='SOME STRING', max_length=10)),
                ('amount_av_min', models.CharField(blank=True, default='SOME STRING', max_length=10)),
                ('amount_av_max', models.CharField(blank=True, default='SOME STRING', max_length=10)),
                ('price_min', models.CharField(blank=True, default='SOME STRING', max_length=10)),
                ('price_max', models.CharField(blank=True, default='SOME STRING', max_length=10)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
