# Generated by Django 3.1 on 2020-09-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalFarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Fruits', 'Veggies'), ('Nuts', 'Honey'), ('Tea', 'Legumes'), ('Oil', 'Wheat'), ('Flowers', 'Mushroom')], default=0, max_length=15),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
