# Generated by Django 3.1 on 2020-09-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalFarm', '0002_snippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='amount_av_max',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='amount_av_min',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='post',
            name='price_max',
        ),
        migrations.RemoveField(
            model_name='post',
            name='price_min',
        ),
    ]
