# Generated by Django 3.1 on 2020-09-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalFarm', '0002_auto_20200909_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='product_type',
        ),
        migrations.AlterField(
            model_name='post',
            name='amount',
            field=models.IntegerField(blank=True, default='SOME STRING'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('nuts', 'Nuts'), ('tea', 'Tea'), ('oil', 'Oil'), ('flowers', 'Flowers'), ('veggies', 'Veggies'), ('honey', 'Honey'), ('legumes', 'Legumes'), ('wheat', 'Wheat'), ('mushroom', 'Mushroom')], default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('Istanbul', 'Istanbul'), ('Denizli', 'Denizli'), ('Aydin', 'Aydin'), ('Izmir', 'Izmir'), ('Antalya', 'Antalya'), ('Rize', 'Rize')], default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(blank=True, default='SOME STRING'),
        ),
        migrations.AlterField(
            model_name='post',
            name='product',
            field=models.CharField(choices=[('apple', 'apple'), ('orange', 'orange'), ('strawberry', 'strawberry'), ('coconut', 'coconut'), ('watermelon', 'watermelon'), ('banana', 'banana'), ('peach', 'peach'), ('kiwi', 'kiwi'), ('avocado', 'avocado'), ('cherry', 'cherry')], default=0, max_length=15),
        ),
    ]
